name: Tests
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[tests]'

      - name: flake8
        run: flake8 src tests *.py

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[tests]'
      - name: Test with pytest
        run: pytest -vv tests